name: Test Project


on:
  pull_request:
    branches: [ main, master ]
jobs:
  test: 
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm test
      - name: build
        run: npm run build



